backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Пост'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Подзаголовок', name: 'excerpt', widget: 'string' }
      - { label: 'Категория', name: 'category', widget: 'string' }
      - {
          label: 'Тэги',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Тэг', name: 'tag', widget: 'string' },
        }
      - { label: 'Изображение', name: 'image', widget: 'string' }
      - { label: 'Дата публикации', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Автор', name: 'author', widget: 'string' }
      - { label: 'Содержимое', name: 'body', widget: 'markdown' }
  - name: 'product'
    label: 'Продукт'
    folder: 'src/content/product'
    create: true
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Подзаголовок', name: 'excerpt', widget: 'string' }
      - { label: 'Тип', name: 'type', widget: 'string' }
      - {
          label: 'Типы',
          name: 'types',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Тип', name: 'type', widget: 'string' },
        }
      - { label: 'Изображение', name: 'image', widget: 'string' }
      - { label: 'Дата публикации Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Содержимое', name: 'body', widget: 'markdown' }
